# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yard-mongoid` gem.
# Please instead update this file by running `tapioca sync`.

# typed: true

module YARD
  class << self
    def load_plugins; end
    def parse(*args); end
    def parse_string(*args); end
    def ruby18?; end
    def ruby19?; end
    def ruby2?; end
    def windows?; end
  end
end

YARD::CONFIG_DIR = T.let(T.unsafe(nil), String)

module YARD::Handlers
end

module YARD::Handlers::Ruby
end

module YARD::Handlers::Ruby::Mongoid
end

module YARD::Handlers::Ruby::Mongoid::Extensions

  protected

  def effected_namespace; end
end

class YARD::Handlers::Ruby::Mongoid::FieldHandler < ::YARD::Handlers::Ruby::AttributeHandler
  include(::YARD::Handlers::Ruby::Mongoid::Extensions)
  include(::YARD::Handlers::Ruby::Mongoid::Helpers)

  def process; end

  protected

  def add_field_change(namespace, name); end
  def add_field_changed(namespace, name); end
  def add_field_getter(namespace, name, type = T.unsafe(nil), default_value = T.unsafe(nil)); end
  def add_field_method(namespace, name); end
  def add_field_presence(namespace, name); end
  def add_field_setter(namespace, name, type = T.unsafe(nil)); end
  def class_name; end
  def default_value; end
  def hash_args; end
  def register_field_reset(namespace, name); end
  def register_field_was(namespace, name); end
end

YARD::Handlers::Ruby::Mongoid::FieldHandler::MONGOID_FIELDS = T.let(T.unsafe(nil), String)

module YARD::Handlers::Ruby::Mongoid::Helpers
  def get_tag(tag, text, return_classes = T.unsafe(nil), name = T.unsafe(nil)); end
end

module YARD::Handlers::Ruby::Mongoid::Relations
end

class YARD::Handlers::Ruby::Mongoid::Relations::Base < ::YARD::Handlers::Ruby::MethodHandler
  include(::YARD::Handlers::Ruby::Mongoid::Helpers)

  def group_name; end
  def process; end

  private

  def class_name(singularize = T.unsafe(nil)); end
  def method_name; end
  def return_description; end
end

class YARD::Handlers::Ruby::Mongoid::Relations::BelongsToHandler < ::YARD::Handlers::Ruby::Mongoid::Relations::SingularHandler
  def group_name; end

  private

  def return_description; end
end

class YARD::Handlers::Ruby::Mongoid::Relations::HasManyHandler < ::YARD::Handlers::Ruby::Mongoid::Relations::PluralHandler
  def group_name; end

  private

  def return_description; end
end

class YARD::Handlers::Ruby::Mongoid::Relations::HasOneHandler < ::YARD::Handlers::Ruby::Mongoid::Relations::SingularHandler
  def group_name; end

  private

  def return_description; end
end

class YARD::Handlers::Ruby::Mongoid::Relations::PluralHandler < ::YARD::Handlers::Ruby::Mongoid::Relations::Base
  def class_name; end

  private

  def return_description; end
end

class YARD::Handlers::Ruby::Mongoid::Relations::SingularHandler < ::YARD::Handlers::Ruby::Mongoid::Relations::Base
  def class_name; end

  private

  def return_description; end
end

module YARD::Mongoid
end

YARD::Mongoid::VERSION = T.let(T.unsafe(nil), String)

YARD::ROOT = T.let(T.unsafe(nil), String)

YARD::TEMPLATE_ROOT = T.let(T.unsafe(nil), String)

YARD::VERSION = T.let(T.unsafe(nil), String)
